--
-- CockroachDB dump
--
-- Synthetic fixture. Every name, address and value below is invented for
-- testing and refers to no real person, company or account.
--
-- Generated by `cockroach dump shop --insecure`.

SET sql_safe_updates = false;

CREATE TABLE public.customers (
    id INT8 NOT NULL DEFAULT unique_rowid(),
    full_name STRING NOT NULL,
    email STRING NULL,
    signed_up_at TIMESTAMP NULL DEFAULT now():::TIMESTAMP,
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    FAMILY "primary" (id, full_name, email, signed_up_at)
);

INSERT INTO customers (id, full_name, email, signed_up_at) VALUES
    (1, 'Alice Example', 'alice@example.test', '2024-01-15 10:30:00'),
    (2, 'Renée Example', NULL, '2024-02-20 14:45:00'),
    (3, 'Charlie Example', 'charlie@example.test', '2024-03-10 09:15:00');

CREATE TABLE public.orders (
    id INT8 NOT NULL DEFAULT unique_rowid(),
    customer_id INT8 NOT NULL,
    note STRING NULL,
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES public.customers (id),
    FAMILY "primary" (id, customer_id, note)
);

INSERT INTO orders (id, customer_id, note) VALUES
    (1, 1, 'Ships to depot, invoice #A-100'),
    (2, 2, NULL);
