REM Oracle SQL script
REM
REM Synthetic fixture. Every name, address and value below is invented for
REM testing and refers to no real person, company or account.
REM
PROMPT Creating the SHOP schema

ALTER SESSION SET CURRENT_SCHEMA = SHOP;

CREATE TABLE SHOP.CUSTOMERS (
  ID         NUMBER(10) NOT NULL,
  FULL_NAME  VARCHAR2(120 CHAR) NOT NULL,
  EMAIL      VARCHAR2(160 CHAR),
  SIGNED_UP  TIMESTAMP WITH TIME ZONE,
  NOTES      CLOB,
  CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
);

CREATE SEQUENCE SHOP.CUSTOMERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO SHOP.CUSTOMERS (ID, FULL_NAME, EMAIL, NOTES) VALUES (1, 'Alice Example', 'alice@example.test', 'Prefers email; not phone.');
INSERT INTO SHOP.CUSTOMERS (ID, FULL_NAME, EMAIL, NOTES) VALUES (2, 'Bob Example', NULL, NULL);
INSERT INTO SHOP.CUSTOMERS (ID, FULL_NAME, EMAIL, NOTES) VALUES (3, 'Zoë Example', 'zoe@example.test', 'Ships to São Paulo');

CREATE INDEX SHOP.IDX_CUSTOMERS_EMAIL ON SHOP.CUSTOMERS (EMAIL);

CREATE TABLE SHOP.ORDERS (
  ID        NUMBER(10) NOT NULL,
  "Order"   VARCHAR2(80),
  TOTAL     NUMBER(12,2) DEFAULT 0,
  CONSTRAINT PK_ORDERS PRIMARY KEY (ID)
);

INSERT INTO SHOP.ORDERS (ID, "Order", TOTAL) VALUES (1, 'Widget crate', 129.50);
INSERT INTO SHOP.ORDERS (ID, "Order", TOTAL) VALUES (2, 'O''Brien pattern washers', 44.00);

ALTER TABLE SHOP.ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (ID) REFERENCES SHOP.CUSTOMERS (ID);

CREATE OR REPLACE TRIGGER SHOP.CUSTOMERS_BI
BEFORE INSERT ON SHOP.CUSTOMERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SHOP.CUSTOMERS_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
  END IF;
END;
/

COMMIT;
