/* Firebird SQL script */
/*
 * Synthetic fixture. Every name, address and value below is invented for
 * testing and refers to no real person, company or account.
 */

CREATE DATABASE 'library.fdb' PAGE_SIZE 8192;

CREATE GENERATOR GEN_AUTHORS_ID;
CREATE GENERATOR GEN_BOOKS_ID;

CREATE TABLE AUTHORS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    "Full Name" VARCHAR(200),
    EMAIL VARCHAR(150),
    NOTES VARCHAR(500),
    CONSTRAINT PK_AUTHORS PRIMARY KEY (ID)
);

CREATE TABLE BOOKS (
    ID INTEGER NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    PRICE DECIMAL(10,2) DEFAULT 0,
    CHECKSUM CHAR(8) CHARACTER SET OCTETS,
    CONSTRAINT PK_BOOKS PRIMARY KEY (ID)
);

CREATE TABLE BORROWINGS (
    ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    BORROWED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BORROWINGS PRIMARY KEY (ID)
);

SET TERM ^ ;

CREATE TRIGGER AUTHORS_BI FOR AUTHORS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
  BEGIN
    NEW.ID = GEN_ID(GEN_AUTHORS_ID, 1);
  END
  IF (NEW.EMAIL IS NULL) THEN
  BEGIN
    NEW.EMAIL = 'unknown@example.test';
  END
END^

CREATE TRIGGER BOOKS_BI FOR BOOKS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
  BEGIN
    NEW.ID = GEN_ID(GEN_BOOKS_ID, 1);
  END
END^

CREATE PROCEDURE GET_BOOK_COUNT (P_AUTHOR_ID INTEGER)
RETURNS (BOOK_COUNT INTEGER)
AS
BEGIN
  SELECT COUNT(*) FROM BOOKS WHERE AUTHOR_ID = :P_AUTHOR_ID INTO :BOOK_COUNT;
  SUSPEND;
END^

SET TERM ; ^

CREATE UNIQUE INDEX IDX_AUTHORS_EMAIL ON AUTHORS (EMAIL);
CREATE INDEX IDX_BOOKS_TITLE ON BOOKS (TITLE);

ALTER TABLE BOOKS ADD CONSTRAINT FK_BOOKS_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID);
ALTER TABLE BORROWINGS ADD CONSTRAINT FK_BORROWINGS_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID);

INSERT INTO AUTHORS (ID, NAME, EMAIL, NOTES) VALUES (1, 'Alice Example', 'alice@example.test', 'Prefers email; not phone.');
INSERT INTO AUTHORS (ID, NAME, EMAIL, NOTES) VALUES (2, 'Bob Example', NULL, 'Ships to São Paulo');
INSERT INTO AUTHORS (ID, NAME, EMAIL, NOTES) VALUES (3, 'O''Malley Example', NULL, NULL);

INSERT INTO BOOKS VALUES (1, 'The Great Adventure', 1, 19.99, X'DEADBEEF');
INSERT INTO BOOKS VALUES (2, 'Über die Bücher', 2, 29.95, X'CAFEBABE');

GRANT SELECT ON AUTHORS TO PUBLIC;
GRANT SELECT ON BOOKS TO PUBLIC;

ALTER SEQUENCE GEN_AUTHORS_ID RESTART WITH 4;

COMMIT WORK;
